server {
    listen 80;
    server_name _;

    location /dav {
        alias /var/www/webdav;

        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_access user:rw group:rw all:r;
        create_full_put_path on;
        autoindex on;
        client_max_body_size 128m;

        # 注意：此处**没有** dav_ext_methods PROPFIND OPTIONS;
        # 缺失是刻意的，见 Dockerfile 注释。
    }
}
